### ISSUE TITLE
super() does not work properly with @storable_* decorators (2.x only?)

### ISSUE THREAD

**Issue by e3krisztian** [e3krisztian/omlite#3]
The symptom is endless recursion, similar to the one described in http://stackoverflow.com/questions/2542747/class-decorators-inheritance-super-and-maximum-recursion

The decorators return a new class that are different, than the class where the functions are defined.

The mandatory passing of the current class as parameter is the cause, as it is given by name, however the class name is bound to another class - the decorated one.

As python 3.\* has `super()` without parameters, this should not be a problem there.

**Comment by krisztianfekete** [comment]
test: https://github.com/krisztianfekete/omlite/commit/d77efcd8de5b0f206d7ddd80d6473392a7d6e13c
fix: https://github.com/krisztianfekete/omlite/commit/5e8bdea048c23dde0dabe358732f0596e57b353c
